---
### Config settings for frag grenade
Frag:
  ### Choose whether blocks break on explosion
  Block-break: false
  ### Choose grenade damage
  Damage: 10
  ### Choose grenade range
  Range: 5
  ### Choose grenade explosion size
  Explosion-size: 4
### Config settings for stun grenade
Stun:
  ### Choose whether blocks break on explosion
  Block-break: false
  ### Choose grenade damage
  Damage: 0
  ### Choose grenade range
  Range: 6
  ### Choose grenade explosion size
  Explosion-size: 2
...
